# Generated by Django 3.1 on 2020-08-07 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Seccion', '0001_initial'),
        ('Grado', '0001_initial'),
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_ins', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('alumno_id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumno.alumno')),
                ('grado_id_grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grado.grado')),
                ('seccion_id_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seccion.seccion')),
            ],
        ),
    ]
