# Generated by Django 3.1 on 2020-08-07 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alumno', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='FechaNacimiento',
        ),
    ]
